name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  google_maps_flutter: ^2.5.0
  flutter_dotenv: ^5.0.2 
  provider: ^6.1.2
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0   
  permission_handler: ^11.3.0
  location: ^5.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_cancellable_tile_provider: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-damkar.png
    - assets/images/Fire_Truck.jpeg
    - assets/images/water_tanker.jpeg
    - assets/images/rescue_car.png
    - assets/images/ambulance.jpg
    - assets/images/Hazmat_Truck.jpg
    - assets/images/Ladder_Truck.jpg
    - assets/images/1.jpeg
    - assets/images/2.jpeg
    - assets/images/3.jpeg
    - assets/images/tutorial.jpeg

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-damkar.png"
